version: '2'
services:
  follows_service:
    build: .
    image: follows_service
    depends_on: 
      - zookeeper
      - kafka
      - db
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "followers"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:12.1
    restart: always
    environment: 
      POSTGRES_PASSWORD: Uz2Vn2Wr
      POSTGRES_USER: olyapashneva
      POSTGRES_DB: follows_service_repo