version: '3.7'
services:
  follows_service:
    build: .
    image: follows_service
    depends_on: 
      - zookeeper
      - kafka
      - db
    environment:
      WAIT_HOSTS: db:5432
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.65.1
      KAFKA_CREATE_TOPICS: "followers"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "follows_topic:1:1:compact,follows_num_topic:1:1,
      follows_all_topic:1:1,follow_topic:1:1,unfollow_topic:1:1,followers_num_topic:1:1,followers_all_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # db:
  #   image: postgres:12.1
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   hostname: localhost
  #   environment: 
  #     POSTGRES_PASSWORD: Uz2Vn2Wr
  #     POSTGRES_USER: olyapashneva
  #     POSTGRES_DB: follows_service_repo
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: follows_service_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    hostname: db
    ports:
      - "5432:5432"